apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: moz-backstage-app
  description: An example of a Backstage application.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: engineering
  lifecycle: experimental
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: engineering
  description: The default group for PoC
spec:
  type: business-unit
